### PR TITLE
update top and bottom PCB silkscreen to v1.3a to match user_adapter PCB

### PR DESCRIPTION
**Pull request by gx1400**

### CODE REVIEW

**Comment by gx1400** [comment]
image

**Comment by gx1400** [comment]
image

**Comment by gx1400** [comment]
image

**Comment by SmittyHalibut** [comment]
Bah!  I'm so sorry for not seeing this earlier!  I do appreciate your pull request, I really do!

Halibut Electronics just went to order a new batch of boards and noticed the same thing, and made this change in d1daf4c1b9cab62a0390933d49ef04145076b7de

Rejecting the PR, but only because I didn't see it before and also made this change.

**Pull request closed without merging**
